# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1172, 910)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(31, 31))
        self.label.setMaximumSize(QtCore.QSize(31, 31))
        self.label.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_R0 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R0.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R0.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R0.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R0.setObjectName("lineEdit_R0")
        self.horizontalLayout.addWidget(self.lineEdit_R0)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(31, 31))
        self.label_3.setMaximumSize(QtCore.QSize(31, 31))
        self.label_3.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_R1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R1.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R1.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R1.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R1.setObjectName("lineEdit_R1")
        self.horizontalLayout_2.addWidget(self.lineEdit_R1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(31, 31))
        self.label_8.setMaximumSize(QtCore.QSize(31, 31))
        self.label_8.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit_R2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R2.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R2.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R2.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R2.setObjectName("lineEdit_R2")
        self.horizontalLayout_7.addWidget(self.lineEdit_R2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(31, 31))
        self.label_7.setMaximumSize(QtCore.QSize(31, 31))
        self.label_7.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_R3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R3.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R3.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R3.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R3.setObjectName("lineEdit_R3")
        self.horizontalLayout_6.addWidget(self.lineEdit_R3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(31, 31))
        self.label_4.setMaximumSize(QtCore.QSize(31, 31))
        self.label_4.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_R4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R4.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R4.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R4.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R4.setObjectName("lineEdit_R4")
        self.horizontalLayout_3.addWidget(self.lineEdit_R4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(31, 31))
        self.label_5.setMaximumSize(QtCore.QSize(31, 31))
        self.label_5.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_R5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R5.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R5.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R5.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R5.setObjectName("lineEdit_R5")
        self.horizontalLayout_4.addWidget(self.lineEdit_R5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(31, 31))
        self.label_9.setMaximumSize(QtCore.QSize(31, 31))
        self.label_9.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_R6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R6.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R6.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R6.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R6.setObjectName("lineEdit_R6")
        self.horizontalLayout_8.addWidget(self.lineEdit_R6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(31, 31))
        self.label_6.setMaximumSize(QtCore.QSize(31, 31))
        self.label_6.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_R7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R7.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_R7.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_R7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_R7.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_R7.setObjectName("lineEdit_R7")
        self.horizontalLayout_5.addWidget(self.lineEdit_R7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(31, 31))
        self.label_12.setMaximumSize(QtCore.QSize(31, 31))
        self.label_12.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.lineEdit_pc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pc.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_pc.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_pc.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_pc.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_pc.setObjectName("lineEdit_pc")
        self.horizontalLayout_11.addWidget(self.lineEdit_pc)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(31, 31))
        self.label_13.setMaximumSize(QtCore.QSize(31, 31))
        self.label_13.setStyleSheet("font: 10pt \"Arial\";\n"
"font: 87 11pt \"Arial\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.lineEdit_bus = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_bus.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_bus.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_bus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_bus.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_bus.setObjectName("lineEdit_bus")
        self.horizontalLayout_12.addWidget(self.lineEdit_bus)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(31, 31))
        self.label_14.setMaximumSize(QtCore.QSize(31, 31))
        self.label_14.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lineEdit_sr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sr.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_sr.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_sr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_sr.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_sr.setObjectName("lineEdit_sr")
        self.horizontalLayout_13.addWidget(self.lineEdit_sr)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(31, 31))
        self.label_15.setMaximumSize(QtCore.QSize(31, 31))
        self.label_15.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.lineEdit_dr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dr.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_dr.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_dr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_dr.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_dr.setObjectName("lineEdit_dr")
        self.horizontalLayout_14.addWidget(self.lineEdit_dr)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(31, 31))
        self.label_16.setMaximumSize(QtCore.QSize(31, 31))
        self.label_16.setStyleSheet("font: 87 11pt \"Arial\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.lineEdit_mar = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mar.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_mar.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_mar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_mar.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_mar.setObjectName("lineEdit_mar")
        self.horizontalLayout_15.addWidget(self.lineEdit_mar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setMinimumSize(QtCore.QSize(31, 31))
        self.label_17.setMaximumSize(QtCore.QSize(31, 31))
        self.label_17.setStyleSheet("font: 87 11pt \"Arial\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.lineEdit_mdr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mdr.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_mdr.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_mdr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_mdr.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_mdr.setObjectName("lineEdit_mdr")
        self.horizontalLayout_16.addWidget(self.lineEdit_mdr)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setMinimumSize(QtCore.QSize(31, 31))
        self.label_18.setMaximumSize(QtCore.QSize(31, 31))
        self.label_18.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.lineEdit_imar = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_imar.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_imar.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_imar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_imar.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_imar.setObjectName("lineEdit_imar")
        self.horizontalLayout_17.addWidget(self.lineEdit_imar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(31, 31))
        self.label_19.setMaximumSize(QtCore.QSize(31, 31))
        self.label_19.setStyleSheet("font: 14pt \"Arial\";\n"
"font: 18pt \"Arial\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.lineEdit_imdr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_imdr.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_imdr.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_imdr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_imdr.setStyleSheet("font: 18pt \"Arial\";")
        self.lineEdit_imdr.setObjectName("lineEdit_imdr")
        self.horizontalLayout_18.addWidget(self.lineEdit_imdr)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_19.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(171, 41))
        self.label_2.setMaximumSize(QtCore.QSize(171, 41))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(191, 341))
        self.listWidget.setMaximumSize(QtCore.QSize(191, 341))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_19.addLayout(self.verticalLayout)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setMinimumSize(QtCore.QSize(171, 41))
        self.label_38.setMaximumSize(QtCore.QSize(171, 41))
        self.label_38.setObjectName("label_38")
        self.verticalLayout_9.addWidget(self.label_38)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setMinimumSize(QtCore.QSize(191, 341))
        self.listWidget_2.setMaximumSize(QtCore.QSize(191, 341))
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_9.addWidget(self.listWidget_2)
        self.horizontalLayout_20.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setMinimumSize(QtCore.QSize(611, 461))
        self.label_20.setMaximumSize(QtCore.QSize(611, 461))
        self.label_20.setStyleSheet("image: url(:/img/i.png);")
        self.label_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_20.setMidLineWidth(20)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.horizontalLayout_23.addLayout(self.verticalLayout_10)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setStyleSheet("font: 12pt \"Arial\";")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setMinimumSize(QtCore.QSize(501, 381))
        self.listWidget_3.setMaximumSize(QtCore.QSize(501, 381))
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_13.addWidget(self.listWidget_3)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setStyleSheet("font: 12pt \"Arial\";")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.listWidget_4 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_4.setMinimumSize(QtCore.QSize(211, 301))
        self.listWidget_4.setMaximumSize(QtCore.QSize(211, 301))
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_11.addWidget(self.listWidget_4)
        self.horizontalLayout_22.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setStyleSheet("font: 12pt \"Arial\";")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.listWidget_5 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_5.setMinimumSize(QtCore.QSize(211, 301))
        self.listWidget_5.setMaximumSize(QtCore.QSize(211, 301))
        self.listWidget_5.setObjectName("listWidget_5")
        self.verticalLayout_12.addWidget(self.listWidget_5)
        self.horizontalLayout_22.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(101, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(101, 41))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_21.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(101, 41))
        self.pushButton_2.setMaximumSize(QtCore.QSize(101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_21.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(101, 41))
        self.pushButton_3.setMaximumSize(QtCore.QSize(101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_21.addWidget(self.pushButton_3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23.addLayout(self.verticalLayout_15)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "通用寄存器"))
        self.label.setText(_translate("MainWindow", "R0"))
        self.lineEdit_R0.setText(_translate("MainWindow", "0000"))
        self.label_3.setText(_translate("MainWindow", "R1"))
        self.lineEdit_R1.setText(_translate("MainWindow", "0000"))
        self.label_8.setText(_translate("MainWindow", "R2"))
        self.lineEdit_R2.setText(_translate("MainWindow", "0000"))
        self.label_7.setText(_translate("MainWindow", "R3"))
        self.lineEdit_R3.setText(_translate("MainWindow", "0000"))
        self.label_4.setText(_translate("MainWindow", "R4"))
        self.lineEdit_R4.setText(_translate("MainWindow", "0000"))
        self.label_5.setText(_translate("MainWindow", "R5"))
        self.lineEdit_R5.setText(_translate("MainWindow", "0000"))
        self.label_9.setText(_translate("MainWindow", "R6"))
        self.lineEdit_R6.setText(_translate("MainWindow", "0000"))
        self.label_6.setText(_translate("MainWindow", "R7"))
        self.lineEdit_R7.setText(_translate("MainWindow", "0000"))
        self.label_11.setText(_translate("MainWindow", "其他寄存器"))
        self.label_12.setText(_translate("MainWindow", "PC"))
        self.lineEdit_pc.setText(_translate("MainWindow", "0000"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">BUS</span></p></body></html>"))
        self.lineEdit_bus.setText(_translate("MainWindow", "0000"))
        self.label_14.setText(_translate("MainWindow", "SR"))
        self.lineEdit_sr.setText(_translate("MainWindow", "0000"))
        self.label_15.setText(_translate("MainWindow", "DR"))
        self.lineEdit_dr.setText(_translate("MainWindow", "0000"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">MAR</span></p></body></html>"))
        self.lineEdit_mar.setText(_translate("MainWindow", "0000"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">MDR</span></p></body></html>"))
        self.lineEdit_mdr.setText(_translate("MainWindow", "0000"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">IMAR</span></p></body></html>"))
        self.lineEdit_imar.setText(_translate("MainWindow", "0000"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">IMDR</span></p></body></html>"))
        self.lineEdit_imdr.setText(_translate("MainWindow", "0000"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">汇编代码</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">机器码</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "控制存储单元"))
        self.label_21.setText(_translate("MainWindow", "微指令序列记录"))
        self.label_22.setText(_translate("MainWindow", "指令存储单元"))
        self.pushButton.setText(_translate("MainWindow", "打开文件"))
        self.pushButton_2.setText(_translate("MainWindow", "单周期执行"))
        self.pushButton_3.setText(_translate("MainWindow", "自律执行"))
import image_rc
