# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 694)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 422, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font: 25 14pt \"Bahnschrift Light\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 11pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a7.setStyleSheet("font: 12pt \"Arial\";")
        self.a7.setObjectName("a7")
        self.horizontalLayout.addWidget(self.a7)
        self.a6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a6.setStyleSheet("font: 12pt \"Arial\";")
        self.a6.setObjectName("a6")
        self.horizontalLayout.addWidget(self.a6)
        self.a5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a5.setStyleSheet("font: 12pt \"Arial\";")
        self.a5.setObjectName("a5")
        self.horizontalLayout.addWidget(self.a5)
        self.a4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a4.setStyleSheet("font: 12pt \"Arial\";")
        self.a4.setObjectName("a4")
        self.horizontalLayout.addWidget(self.a4)
        self.a3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a3.setStyleSheet("font: 12pt \"Arial\";")
        self.a3.setObjectName("a3")
        self.horizontalLayout.addWidget(self.a3)
        self.a2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a2.setStyleSheet("font: 12pt \"Arial\";")
        self.a2.setObjectName("a2")
        self.horizontalLayout.addWidget(self.a2)
        self.a1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a1.setStyleSheet("font: 12pt \"Arial\";")
        self.a1.setObjectName("a1")
        self.horizontalLayout.addWidget(self.a1)
        self.a0 = QtWidgets.QCheckBox(self.layoutWidget)
        self.a0.setStyleSheet("font: 12pt \"Arial\";")
        self.a0.setObjectName("a0")
        self.horizontalLayout.addWidget(self.a0)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("font: 11pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.b7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b7.setStyleSheet("font: 12pt \"Arial\";")
        self.b7.setObjectName("b7")
        self.horizontalLayout_6.addWidget(self.b7)
        self.b6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b6.setStyleSheet("font: 12pt \"Arial\";")
        self.b6.setObjectName("b6")
        self.horizontalLayout_6.addWidget(self.b6)
        self.b5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b5.setStyleSheet("font: 12pt \"Arial\";")
        self.b5.setObjectName("b5")
        self.horizontalLayout_6.addWidget(self.b5)
        self.b4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b4.setStyleSheet("font: 12pt \"Arial\";")
        self.b4.setObjectName("b4")
        self.horizontalLayout_6.addWidget(self.b4)
        self.b3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b3.setStyleSheet("font: 12pt \"Arial\";")
        self.b3.setObjectName("b3")
        self.horizontalLayout_6.addWidget(self.b3)
        self.b2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b2.setStyleSheet("font: 12pt \"Arial\";")
        self.b2.setObjectName("b2")
        self.horizontalLayout_6.addWidget(self.b2)
        self.b1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b1.setStyleSheet("font: 12pt \"Arial\";")
        self.b1.setObjectName("b1")
        self.horizontalLayout_6.addWidget(self.b1)
        self.b0 = QtWidgets.QCheckBox(self.layoutWidget)
        self.b0.setStyleSheet("font: 12pt \"Arial\";")
        self.b0.setObjectName("b0")
        self.horizontalLayout_6.addWidget(self.b0)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 560, 181, 71))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 720, 121, 31))
        self.label_4.setObjectName("label_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(2, 263, 294, 47))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setStyleSheet("font: 25 11pt \"Bahnschrift Light\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_17.setStyleSheet("font: 11pt \"Arial\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.lineEdit_g7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g7.setEnabled(False)
        self.lineEdit_g7.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g7.setObjectName("lineEdit_g7")
        self.verticalLayout_18.addWidget(self.lineEdit_g7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_18)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_18.setStyleSheet("font: 11pt \"Arial\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_17.addWidget(self.label_18)
        self.lineEdit_g6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g6.setEnabled(False)
        self.lineEdit_g6.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g6.setObjectName("lineEdit_g6")
        self.verticalLayout_17.addWidget(self.lineEdit_g6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_19.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_19.setStyleSheet("font: 11pt \"Arial\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_16.addWidget(self.label_19)
        self.lineEdit_g5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g5.setEnabled(False)
        self.lineEdit_g5.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g5.setObjectName("lineEdit_g5")
        self.verticalLayout_16.addWidget(self.lineEdit_g5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_20.setStyleSheet("font: 11pt \"Arial\";")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_15.addWidget(self.label_20)
        self.lineEdit_g4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g4.setEnabled(False)
        self.lineEdit_g4.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g4.setObjectName("lineEdit_g4")
        self.verticalLayout_15.addWidget(self.lineEdit_g4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_21.setStyleSheet("font: 11pt \"Arial\";")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_14.addWidget(self.label_21)
        self.lineEdit_g3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g3.setEnabled(False)
        self.lineEdit_g3.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g3.setObjectName("lineEdit_g3")
        self.verticalLayout_14.addWidget(self.lineEdit_g3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_22.setStyleSheet("font: 11pt \"Arial\";")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.lineEdit_g2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g2.setEnabled(False)
        self.lineEdit_g2.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g2.setObjectName("lineEdit_g2")
        self.verticalLayout_13.addWidget(self.lineEdit_g2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_23.setStyleSheet("font: 11pt \"Arial\";")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.lineEdit_g1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g1.setEnabled(False)
        self.lineEdit_g1.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g1.setObjectName("lineEdit_g1")
        self.verticalLayout_12.addWidget(self.lineEdit_g1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_24.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_24.setStyleSheet("font: 11pt \"Arial\";")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_11.addWidget(self.label_24)
        self.lineEdit_g0 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_g0.setEnabled(False)
        self.lineEdit_g0.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_g0.setObjectName("lineEdit_g0")
        self.verticalLayout_11.addWidget(self.lineEdit_g0)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(2, 208, 294, 47))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setStyleSheet("font: 25 11pt \"Bahnschrift Light\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_9.setStyleSheet("font: 11pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.lineEdit_p7 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p7.setEnabled(False)
        self.lineEdit_p7.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p7.setObjectName("lineEdit_p7")
        self.verticalLayout_3.addWidget(self.lineEdit_p7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_10.setStyleSheet("font: 11pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.lineEdit_p6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p6.setEnabled(False)
        self.lineEdit_p6.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p6.setObjectName("lineEdit_p6")
        self.verticalLayout_4.addWidget(self.lineEdit_p6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_11.setStyleSheet("font: 11pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.lineEdit_p5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p5.setEnabled(False)
        self.lineEdit_p5.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p5.setObjectName("lineEdit_p5")
        self.verticalLayout_5.addWidget(self.lineEdit_p5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_12.setStyleSheet("font: 11pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.lineEdit_p4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p4.setEnabled(False)
        self.lineEdit_p4.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p4.setObjectName("lineEdit_p4")
        self.verticalLayout_6.addWidget(self.lineEdit_p4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_13.setStyleSheet("font: 11pt \"Arial\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.lineEdit_p3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p3.setEnabled(False)
        self.lineEdit_p3.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p3.setObjectName("lineEdit_p3")
        self.verticalLayout_7.addWidget(self.lineEdit_p3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_14.setStyleSheet("font: 11pt \"Arial\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.lineEdit_p2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p2.setEnabled(False)
        self.lineEdit_p2.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p2.setObjectName("lineEdit_p2")
        self.verticalLayout_8.addWidget(self.lineEdit_p2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_15.setStyleSheet("font: 11pt \"Arial\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.lineEdit_p1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p1.setEnabled(False)
        self.lineEdit_p1.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p1.setObjectName("lineEdit_p1")
        self.verticalLayout_9.addWidget(self.lineEdit_p1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_16.setStyleSheet("font: 11pt \"Arial\";")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.lineEdit_p0 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_p0.setEnabled(False)
        self.lineEdit_p0.setMaximumSize(QtCore.QSize(21, 16777215))
        self.lineEdit_p0.setObjectName("lineEdit_p0")
        self.verticalLayout_10.addWidget(self.lineEdit_p0)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(1, 151, 432, 50))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_25.setStyleSheet("font: 12pt \"Arial\";")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_19.addWidget(self.label_25)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setStyleSheet("font: 11pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.c7 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c7.setEnabled(False)
        self.c7.setStyleSheet("font: 12pt \"Arial\";")
        self.c7.setObjectName("c7")
        self.horizontalLayout_7.addWidget(self.c7)
        self.c6 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c6.setEnabled(False)
        self.c6.setStyleSheet("font: 12pt \"Arial\";")
        self.c6.setObjectName("c6")
        self.horizontalLayout_7.addWidget(self.c6)
        self.c5 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c5.setEnabled(False)
        self.c5.setStyleSheet("font: 12pt \"Arial\";")
        self.c5.setObjectName("c5")
        self.horizontalLayout_7.addWidget(self.c5)
        self.c4 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c4.setEnabled(False)
        self.c4.setStyleSheet("font: 12pt \"Arial\";")
        self.c4.setObjectName("c4")
        self.horizontalLayout_7.addWidget(self.c4)
        self.c3 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c3.setEnabled(False)
        self.c3.setStyleSheet("font: 12pt \"Arial\";")
        self.c3.setObjectName("c3")
        self.horizontalLayout_7.addWidget(self.c3)
        self.c2 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c2.setEnabled(False)
        self.c2.setStyleSheet("font: 12pt \"Arial\";")
        self.c2.setObjectName("c2")
        self.horizontalLayout_7.addWidget(self.c2)
        self.c1 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c1.setEnabled(False)
        self.c1.setStyleSheet("font: 12pt \"Arial\";")
        self.c1.setObjectName("c1")
        self.horizontalLayout_7.addWidget(self.c1)
        self.c0 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.c0.setEnabled(False)
        self.c0.setStyleSheet("font: 12pt \"Arial\";")
        self.c0.setObjectName("c0")
        self.horizontalLayout_7.addWidget(self.c0)
        self.verticalLayout_19.addLayout(self.horizontalLayout_7)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(120, 370, 433, 142))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setStyleSheet("font: 25 14pt \"Bahnschrift Light\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_20.addWidget(self.label_2)
        self.lineEdit_result = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_result.setMinimumSize(QtCore.QSize(431, 111))
        self.lineEdit_result.setMaximumSize(QtCore.QSize(431, 16777215))
        self.lineEdit_result.setStyleSheet("font: 36pt \"Bahnschrift SemiLight Condensed\";\n"
"")
        self.lineEdit_result.setText("")
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.verticalLayout_20.addWidget(self.lineEdit_result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "超前位加法器"))
        self.label_6.setText(_translate("MainWindow", "输入数据"))
        self.label.setText(_translate("MainWindow", "加数1"))
        self.a7.setText(_translate("MainWindow", "a7"))
        self.a6.setText(_translate("MainWindow", "a6"))
        self.a5.setText(_translate("MainWindow", "a5"))
        self.a4.setText(_translate("MainWindow", "a4"))
        self.a3.setText(_translate("MainWindow", "a3"))
        self.a2.setText(_translate("MainWindow", "a2"))
        self.a1.setText(_translate("MainWindow", "a1"))
        self.a0.setText(_translate("MainWindow", "a0"))
        self.label_3.setText(_translate("MainWindow", "加数2"))
        self.b7.setText(_translate("MainWindow", "b7"))
        self.b6.setText(_translate("MainWindow", "b6"))
        self.b5.setText(_translate("MainWindow", "b5"))
        self.b4.setText(_translate("MainWindow", "b4"))
        self.b3.setText(_translate("MainWindow", "b3"))
        self.b2.setText(_translate("MainWindow", "b2"))
        self.b1.setText(_translate("MainWindow", "b1"))
        self.b0.setText(_translate("MainWindow", "b0"))
        self.pushButton.setText(_translate("MainWindow", "开始计算"))
        self.label_4.setText(_translate("MainWindow", "华北理工大学--马昕"))
        self.label_8.setText(_translate("MainWindow", "本地进位"))
        self.label_17.setText(_translate("MainWindow", "g7"))
        self.lineEdit_g7.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "g6"))
        self.lineEdit_g6.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "g5"))
        self.lineEdit_g5.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "g4"))
        self.lineEdit_g4.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "g3"))
        self.lineEdit_g3.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "g2"))
        self.lineEdit_g2.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "g1"))
        self.lineEdit_g1.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "g0"))
        self.lineEdit_g0.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "传递进位"))
        self.label_9.setText(_translate("MainWindow", "p7"))
        self.lineEdit_p7.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "p6"))
        self.lineEdit_p6.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "p5"))
        self.lineEdit_p5.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "p4"))
        self.lineEdit_p4.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "p3"))
        self.lineEdit_p3.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "p2"))
        self.lineEdit_p2.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "p1"))
        self.lineEdit_p1.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "p0"))
        self.lineEdit_p0.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "过程信息显示"))
        self.label_5.setText(_translate("MainWindow", "是否进位"))
        self.c7.setText(_translate("MainWindow", "c7"))
        self.c6.setText(_translate("MainWindow", "c6"))
        self.c5.setText(_translate("MainWindow", "c5"))
        self.c4.setText(_translate("MainWindow", "c4"))
        self.c3.setText(_translate("MainWindow", "c3"))
        self.c2.setText(_translate("MainWindow", "c2"))
        self.c1.setText(_translate("MainWindow", "c1"))
        self.c0.setText(_translate("MainWindow", "c0"))
        self.label_2.setText(_translate("MainWindow", "结果显示"))
